// export interface MovieCard {
//     id: number;
//     title: string;
//     posterUrl: string;
// }

// copy the JSON data
// activate/open the extension
// ctrl/cmd shift P
// search for paste as JSON extension

// Generated by https://quicktype.io

export interface MovieCard {
    id:        number;
    title:     string;
    posterUrl: string;
}
